spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movieBookingDB
    username: PETA.R
    password: 15032
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false
  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
server:
  port: 8080